namespace Hotfix {public class ResConst{
//Group：PackTogether ;Label:Code;A;
     public const string dll_Hotfix = "Hotfix.dll.bytes";
//Group：PackTogether ;Label:Code;A;
     public const string pdb_Hotfix = "Hotfix.pdb.bytes";
//Group：PackTogether ;Label:Config;A;
     public const string txt_BuffConfig = "BuffConfig.txt";
//Group：PackTogether ;Label:Config;A;
     public const string txt_CellConfig = "CellConfig.txt";
//Group：PackTogether ;Label:Config;A;
     public const string txt_EssentialShape = "EssentialShape.txt";
//Group：PackTogether ;Label:Config;A;
     public const string txt_EssentialShapePool = "EssentialShapePool.txt";
//Group：PackTogether ;Label:Config;A;
     public const string txt_GlobalProto = "GlobalProto.txt";
//Group：PackTogether ;Label:Config;A;
     public const string txt_SpecialEle = "SpecialEle.txt";
//Group：PackTogether ;Label:Config;A;
     public const string txt_UnitConfig = "UnitConfig.txt";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_SoundPrefab = "SoundPrefab.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_CellBG2D = "CellBG2D.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ClassicCell2D_1 = "ClassicCell2D_1.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ClassicCell2D_10 = "ClassicCell2D_10.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ClassicCell2D_11 = "ClassicCell2D_11.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ClassicCell2D_12 = "ClassicCell2D_12.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ClassicCell2D_13 = "ClassicCell2D_13.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ClassicCell2D_14 = "ClassicCell2D_14.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ClassicCell2D_15 = "ClassicCell2D_15.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ClassicCell2D_2 = "ClassicCell2D_2.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ClassicCell2D_3 = "ClassicCell2D_3.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ClassicCell2D_4 = "ClassicCell2D_4.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ClassicCell2D_5 = "ClassicCell2D_5.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ClassicCell2D_6 = "ClassicCell2D_6.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ClassicCell2D_61 = "ClassicCell2D_61.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ClassicCell2D_62 = "ClassicCell2D_62.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ClassicCell2D_63 = "ClassicCell2D_63.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ClassicCell2D_64 = "ClassicCell2D_64.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ClassicCell2D_7 = "ClassicCell2D_7.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ClassicCell2D_8 = "ClassicCell2D_8.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ClassicCell2D_9 = "ClassicCell2D_9.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ClassicCell2D_Bomb = "ClassicCell2D_Bomb.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ClassicGame2D = "ClassicGame2D.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_Shape2D = "Shape2D.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_Home = "Home.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_HomePlayButton = "HomePlayButton.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ToLevel1 = "ToLevel1.prefab";
//Group：PackTogether ;Label:prefab;A;
     public const string prefab_ToNextLevel = "ToNextLevel.prefab";
//Group：PackTogether ;Label:ui;A;
     public const string prefab_FailDialog = "FailDialog.prefab";
//Group：PackTogether ;Label:ui;A;
     public const string prefab_GameUI = "GameUI.prefab";
//Group：PackTogether ;Label:ui;A;
     public const string prefab_UIManager = "UIManager.prefab";
//Group：PackTogether ;Label:ui;A;
     public const string prefab_WinDialog = "WinDialog.prefab";
//Group：PackSeparately ;Label:sound;A;
     public const string mp3_common_hm = "common_hm.mp3";
//Group：PackSeparately ;Label:sound;A;
     public const string wav_btn_home = "btn_home.wav";
//Group：PackSeparately ;Label:Scene;A;
     public const string unity_Game = "Game.unity";
}}